Repository AY2122S1-CS2103T-W08-1/tp, pull requests merged in 2021-11, with the labels that each got.

#232 Fix: Fix Parsing Errors
  src/main/java/seedu/notor/logic/parser/NotorParser.java
  src/main/java/seedu/notor/model/common/Name.java
  src/test/java/seedu/notor/model/person/NameTest.java
Labels: bug

#234 Fix: Groups Not Updating When Person is Deleted/Archived
  src/main/java/seedu/notor/model/ModelManager.java
Labels: bug

#237 Docs: Update DeveloperGuide.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
Labels: documentation

#236 Fix documentation bugs in UG
  docs/UserGuide.md
Labels: bug, documentation

#245 Docs: Update yukun99.md
  docs/team/yukun99.md
Labels: documentation

#248 Fix: Allow Single Letter Names
  src/main/java/seedu/notor/logic/parser/NotorParser.java
  src/test/java/seedu/notor/logic/parser/PersonDeleteCommandParserTest.java
Labels: bug, hacktoberfest-accepted

#252 Docs: Elton v1.4 effort
  docs/DeveloperGuide.md
Labels: documentation
