Repository AY2122S1-CS2103T-W08-1/tp, pull requests merged in 2021-10, with the labels that each got.

#61 Add User Stories and Use Cases to Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/img.png
Labels: documentation, help wanted, priority.high

#60 Update NFRs and Glossary
  docs/DeveloperGuide.md
Labels: documentation, priority.high

#67 Docs: Fix YAML Error and Edit Docs to Pass TP Checks
  docs/AboutUs.md
  docs/_config.yml
  docs/images/halphasx.jpg
  docs/images/halphasx.png
  docs/team/elroygohjy.md
  docs/team/eltongohjh.md
  docs/team/halphasx.md
  docs/team/johndoe.md
  docs/team/kaixin-hc.md
  docs/team/yukun99.md
Labels: bug, documentation

#71 Docs: Remove AB3 changes in UserGuide
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: bug, documentation

#74 Chore: Fix DG and _config.yml
  docs/DeveloperGuide.md
  docs/_config.yml
Labels: bug, documentation, priority.high

#75 Remove AB3 - Fix YAML Errors
  docs/AboutUs.md
  docs/Configuration.md
  docs/DevOps.md
  docs/DeveloperGuide.md
  docs/Documentation.md
  docs/Logging.md
  docs/SettingUp.md
  docs/Testing.md
  docs/UserGuide.md
  docs/assets/css/style.scss
  docs/images/add-remark/$Remark.png
  docs/images/add-remark/CommandInterface.png
  docs/images/add-remark/ContextMenu.png
  docs/images/add-remark/CreateTest.png
  docs/images/add-remark/GradleRun.png
  docs/images/add-remark/ParserInterface.png
  docs/images/add-remark/RemarkBound.png
  docs/images/add-remark/RemarkComplete.png
  docs/images/add-remark/RemarkFailureOutput.png
  docs/images/add-remark/RemarkHello.png
  docs/images/add-remark/RemarkNotImplemented.png
  docs/images/remove/$address.png
  docs/images/remove/SafeDeleteConflicts.png
  docs/images/remove/UnsafeDelete.png
  docs/images/remove/UnsafeDeleteOnField.png
  docs/img.png
  docs/index.md
  docs/team/elroygohjy.md
  docs/team/eltongohjh.md
  docs/team/halphasx.md
  docs/team/johndoe.md
  docs/team/kaixin-hc.md
  docs/team/yukun99.md
Labels: hacktoberfest-accepted

#90 Feat: Add Note Command, Add Note UI & Add Note Date Saving
  src/main/java/seedu/address/commons/util/DateUtil.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/person/PersonNoteCommand.java
  src/main/java/seedu/address/logic/executors/person/PersonEditExecutor.java
  src/main/java/seedu/address/logic/executors/person/PersonNoteExecutor.java
  src/main/java/seedu/address/logic/parser/person/PersonCreateCommandParser.java
  src/main/java/seedu/address/logic/parser/person/PersonNoteCommandParser.java
  src/main/java/seedu/address/model/person/Note.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/NoteWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/NoteWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/PersonNoteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/PersonNoteCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: enhancement, priority.high, hacktoberfest-accepted, gui

#100 Update UserGuide.md
  docs/UserGuide.md
Labels: bug, documentation, priority.high, hacktoberfest-accepted

#117 Docs: Update Group Commands in UG
  docs/UserGuide.md
Labels: documentation, hacktoberfest-accepted

#130 Docs: Update DeveloperGuide.md with Command Changes
  docs/DeveloperGuide.md
Labels: documentation

#139 Docs: Fix UG Bugs
  docs/Documentation.md
  docs/UserGuide.md
  docs/_sass/minima/_base.scss
  docs/diagrams/UndoRedoState5.puml
  docs/images/UndoRedoState5.png
  docs/images/helpMessage.png
Labels: documentation, hacktoberfest-accepted
